// import the library
import { library } from '@fortawesome/fontawesome-svg-core';

// import your icons
import {
  faQuestionCircle,
  faTools,
  faSignInAlt,
  faUsers,
  faDice,
  faPaperPlane,
  faCog,
  faAddressCard,
  faPlusSquare,
  faPenSquare,
  faHeart,
  faFlask,
  faWindowClose,
  faUserPlus,
  faUserCog,
  faUser,
  faTimes,
  faCheck,
  faChessQueen,
  faChessPawn,
  faDragon,
  faDoorOpen,
  faPaperclip,
  faUpload,
  faMapMarkedAlt,
  faComments
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faQuestionCircle,
  faTools,
  faSignInAlt,
  faUsers,
  faDice,
  faPaperPlane,
  faCog,
  faAddressCard,
  faPlusSquare,
  faPenSquare,
  faHeart,
  faFlask,
  faWindowClose,
  faUserPlus,
  faUserCog,
  faUser,
  faTimes,
  faCheck,
  faChessQueen,
  faChessPawn,
  faDragon,
  faDoorOpen,
  faPaperclip,
  faUpload,
  faMapMarkedAlt,
  faComments
);
