export const ADD_TO_CHAT_LOG = 'ADD_TO_CHAT_LOG';
export const ADD_TO_CHAR_LIST = 'ADD_TO_CHAR_LIST';
export const REMOVE_FROM_CHAR_LIST = 'REMOVE_FROM_CHAR_LIST';
export const TOGGLE_CHAR_LIST = 'TOGGLE_CHAR_LIST';
export const TOGGLE_DICE_BUBBLE = 'TOGGLE_DICE_BUBBLE';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
